services:
  app:
    image: ${DOCKER_USERNAME}/garopabus-backend:${IMAGE_TAG}
    container_name: ${APP_CONTAINER_NAME}-backend
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER_NAME}:${POSTGRES_PORT}/${POSTGRES_DB}  # Usando o nome do container do PostgreSQL
    volumes:
      - ./staticfiles:/app/staticfiles

  postgres:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}  # Nome do container do PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
