# Generated by Django 5.1.3 on 2024-11-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PontoOnibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('link_maps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_variacao', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('variacao', 'Variação')], max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('sql_executado', models.TextField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='PontoTrajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('id_rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.rota')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioOnibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('dia_util', 'Dia Util'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_partida', models.DateTimeField()),
                ('hora_chegada', models.DateTimeField()),
                ('id_rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.rota')),
            ],
        ),
        migrations.CreateModel(
            name='RotaPontoOnibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('id_ponto_onibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.pontoonibus')),
                ('id_rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.rota')),
            ],
        ),
    ]
