# Generated by Django 5.1.3 on 2024-11-08 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id_administrador',
        ),
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='sql_executado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
