# Generated by Django 5.1.3 on 2024-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_delete_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='nome',
            new_name='bairro_destido',
        ),
        migrations.AddField(
            model_name='rota',
            name='bairro_origem',
            field=models.CharField(default='centro', max_length=100),
            preserve_default=False,
        ),
    ]
