# Generated by Django 5.1.3 on 2024-11-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_rename_nome_rota_bairro_destido_rota_bairro_origem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='bairro_destido',
            new_name='bairro_destino',
        ),
    ]
