# Generated by Django 5.1.3 on 2024-12-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_alter_horarioonibus_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='id_rota_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.rota'),
        ),
    ]
