# Generated by Django 5.1.3 on 2024-12-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0011_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
